# configuration for "master" branch
# build in Release mode and deploy to nuget
-  
  branches:
    only:
      - master

  version: 2.1.{build}

  configuration: Release
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  
  before_build:
  - cmd: nuget restore Scenarioo-cs.sln
  
  build:
    publish_nuget: true
    verbosity: normal
  
  deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: 74aGO6tf6vNU0RRESbiWpDc10ZzZMETG02KpQedI/Ecnnx8yMoZknu/SdUP0BaMk

-  
  branches:
    only:
      - /pull/.*/

  version: 2.1.{build}
  
  pull_requests:
    do_not_increment_build_number: true

  configuration: Release
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  
  before_build:
  - cmd: nuget restore Scenarioo-cs.sln
  
  build:
    publish_nuget: false
    verbosity: normal

# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing. no nuget publish
-
  branches:
    only:
      - /dev-.*/
      - /dev.*/

  version: 3.0.{build}

  configuration: Release
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  
  before_build:
  - cmd: nuget restore Scenarioo-cs.sln
  
  build:
    publish_nuget: true
    verbosity: normal

-
  branches:
    only:
      - /feature/.*/

  version: 3.0.{build}

  configuration: Release

  pull_requests:
    do_not_increment_build_number: true
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  
  before_build:
  - cmd: nuget restore Scenarioo-cs.sln
  
  build:
    publish_nuget: false
    verbosity: normal

-
  branches:
    only:
	  - /release/.*/
    
  version: 2.1.{build}-rc
    
  configuration: Release
  
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  
  before_build:
  - cmd: nuget restore
  
  build:
    publish_nuget: true
    verbosity: normal

  deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: 74aGO6tf6vNU0RRESbiWpDc10ZzZMETG02KpQedI/Ecnnx8yMoZknu/SdUP0BaMk

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Release