# restore Nuget packages before running MSBuild
before_build:
  - nuget restore
  
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    
#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: Scenarioo-cs.sln      # path to Visual Studio solution or project
  publish_nuget: true                         # package projects with .nuspec files and push to artifacts
  
  # MSBuild verbosity level
  verbosity: detailed


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - ScenariooTest.dll
