-  
  branches:
    only:
      - master
      - dev
  configuration: Release
  platform: Any CPU
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  install:
    - choco install gitversion.portable -y

  before_build:
  - ps: nuget restore Scenarioo-cs.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  
  build:
    publish_nuget: true
    verbosity: normal
  
  deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/scenarioo
    api_key:
      secure: Mh+LngNbJyjY1/z+s9Vzdey6WbwSmvrIvyAj4zpURtc=k

# feature branches are pushed to appveyor nuget feed, may be used for testing.
- 
  branches:
    only:
      - /feature/.*/
  configuration: Release
  platform: Any CPU
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  install:
    - choco install gitversion.portable -y

  before_build:
  - ps: nuget restore Scenarioo-cs.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  
  build:
    publish_nuget: true
    verbosity: normal
  
  deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/scenarioo
    api_key:
      secure: Mh+LngNbJyjY1/z+s9Vzdey6WbwSmvrIvyAj4zpURtc=k

- 
  branches:
    only:
      - /.*/merge/
  configuration: Release
  platform: Any CPU
  cache:
    - packages -> **\packages.config
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml
  install:
    - choco install gitversion.portable -y
  before_build:
  - ps: nuget restore Scenarioo-cs.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  
  build:
    publish_nuget: true
    verbosity: normal

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Release