-  
  branches:
    only:
      - master
      - dev
  environment:
    private_nuget_api_key:
      secure: Mh+LngNbJyjY1/z+s9Vzdey6WbwSmvrIvyAj4zpURtc=k
  
  configuration: Release
  platform: Any CPU
  
  install:
    - choco install gitversion.portable -y

  before_build:
  - ps: nuget restore Scenarioo-cs.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  
  build:
    publish_nuget: true
    verbosity: normal
  
  after_build:
    - ps: nuget pack src\Scenarioo\Scenarioo.csproj -Version (get-item env:GitVersion_NuGetVersionV2).Value -properties "Configuration=$env:configuration;Platform=AnyCPU" -Verbosity Detailed -Build
    - ps: nuget push *.nupkg -ApiKey (get-item env:private_nuget_api_key).Value -Source https://ci.appveyor.com/nuget/scenarioo/api/v2/package