# restore Nuget packages before running MSBuild
before_build:
  - nuget restore
  
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    
#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform: AnyCPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - AnyCPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release
    
build:
  project: *\Scenarioo-cs.sln      # path to Visual Studio solution or project
  publish_nuget: true                         # package projects with .nuspec files and push to artifacts
  
  # MSBuild verbosity level
  verbosity: detailed


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - *\ScenariooTest.dll
