# restore Nuget packages before running MSBuild
before_build:
  - nuget restore
  
build:
  publish_nuget: true                         # package projects with .nuspec files and push to artifacts
  
  # MSBuild verbosity level
  verbosity: detailed


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - ScenariooTest.dll
